#!/usr/bin/env ruby
# encoding: UTF-8

# http://www.wpi.edu/Pubs/E-project/Available/E-project-122610-202225/unrestricted/FinalReport_B10.pdf
# https://sites.google.com/site/informazionisuituttinegozi/

require 'httpclient'
require 'firebase'
require 'json'
require 'active_support/all'

SRC = "https://ckdata.firebaseio.com/"
KEY = "6oHOTzpyRjbzO5HP7EQWclxwICXPOOv7UJpZqZFe"
FB = Firebase::Client.new(SRC, KEY)

def import(section, l1, l2, l3, l4, descr, descr_bief)
  if [section, l1, l2, l3, l4].join('').size > 1
    codes = [section, l1, l2, l3, l4].map{|i| i.to_s.size > 0 ? i : nil}.compact
    data = {
      :nace => codes.join('.'),
      :descr => descr
    }
    data[:nace_plus ] = codes.join('.') if l3.to_s.size > 0
    data[:descr_plus] = descr_bief if descr_bief.to_s.size > 1
    FB.update("nace_plus/#{codes.join('_')}", data)
  end
end

# import('Section', 'L1', 'L2', 'L3', 'L4', 'Description', '')
import('Z', '', '', '', '', 'Closed stores', '')
import('', '0', '0', '', '', 'Closed stores', 'Closed')
import('', '', '', '', '', '', '')
import('G', '', '', '', '', 'Wholesale and retail trade; repair of motor vehicles, motorcycles and personal and household goods', '')
import('G', '52', '', '', '', 'Retail trade, except of motor vehicles and motorcycles; repair of personal and household goods  ', '')
import('G', '52', '1', '', '', 'Retail sale in non-specialized stores  ', '')
import('G', '52', '1', '1', '', 'Retail sale in non-specialized stores with food, beverages or tobacco predominating  ', 'Grocery Store')
import('G', '52', '1', '2', '', 'Other retail sale in non-specialized stores  ', 'General Store')
import('G', '52', '2', '', '', 'Retail sale of food, beverages and tobacco in specialized stores  ', '')
import('G', '52', '2', '1', '', 'Retail sale of fruit and vegetables  ', 'Produce')
import('G', '52', '2', '2', '', 'Retail sale of meat and meat products  ', 'Butcher')
import('G', '52', '2', '3', '', 'Retail sale of fish, crustaceans and molluscs  ', 'Seafood')
import('G', '52', '2', '4', '', 'Retail sale of bread, cakes, flour confectionery and sugar confectionery  ', '')
import('G', '52', '2', '4', '1', 'Retail sale of bread, cakes, and flour confectionery', 'Bakery')
import('G', '52', '2', '4', '2', 'Retail sale of sugar confections', 'Candy')
import('G', '52', '2', '5', '', 'Retail sale of alcoholic and other beverages  ', '')
import('G', '52', '2', '5', '1', 'Retail sale of alcoholic and other beverages  ', 'Liquor')
import('', '52', '2', '5', '2', 'Retail sale of wine', 'Wine')
import('G', '52', '2', '6', '', 'Retail sale of tobacco products  ', 'Tobacco')
import('G', '52', '2', '7', '', 'Other retail sale of food, beverages and tobacco in specialized stores  ', '')
import('G', '52', '2', '7', '1', 'Retail sale of dairy and dairy products', 'Dairy')
import('G', '52', '2', '7', '2', 'Retail sale of coffee and coffee products', 'Coffee')
import('G', '52', '3', '', '', 'Retail sale of pharmaceutical and medical goods, cosmetic and toilet articles  ', '')
import('G', '52', '3', '1', '', 'Dispensing chemists', 'Pharmacy')
import('G', '52', '3', '2', '', 'Retail sale of medical and orthopaedic goods  ', 'Medical Goods')
import('G', '52', '3', '3', '', 'Retail sale of cosmetic and toilet articles  ', 'Cosmetics')
import('G', '52', '3', '3', '1', 'Retail sale of perfume', 'Perfume')
import('G', '52', '4', '', '', 'Other retail sale of new goods in specialized stores  ', '')
import('G', '52', '4', '1', '', 'Retail sale of textiles  ', 'Textiles')
import('G', '52', '4', '2', '', 'Retail sale of clothing  ', 'Clothing')
import('G', '52', '4', '2', '1', 'Retail sale of luxury items', 'Luxury')
import('G', '52', '4', '2', '2', 'Retail sale of undergarments', 'Undergarments')
import('G', '52', '4', '2', '3', 'Retail sale of accessories', 'Accessories')
import('G', '52', '4', '3', '', 'Retail sale of footwear and leather goods  ', '')
import('G', '52', '4', '3', '1', 'Retail sale of footware', 'Shoes')
import('G', '52', '4', '3', '2', 'Retail sale of leather goods', 'Leather Goods')
import('G', '52', '4', '3', '3', 'Retail sale of gloves', 'Gloves')
import('G', '52', '4', '4', '', 'Retail sale of furniture, lighting equipment and household articles n.e.c.  ', '')
import('G', '52', '4', '4', '1', 'Retail sale of furniture', 'Furniture')
import('G', '52', '4', '4', '2', 'Retail sale of household articles/decoration', 'Household Goods')
import('G', '52', '4', '4', '3', 'Retail sale of lighting equipment', '')
import('G', '52', '4', '4', '4', 'Retail sale of assorted items', '')
import('G', '52', '4', '5', '', 'Retail sale of electrical household appliances and radio and television goods  ', '')
import('G', '52', '4', '5', '1', 'Retail sale of radio and television goods', 'Radio and Television')
import('G', '52', '4', '5', '2', 'Retail sale of computer and computer goods', 'Computer')
import('G', '52', '4', '5', '3', 'Retail sale of electronics', 'Electronics')
import('G', '52', '4', '6', '', 'Retail sale of hardware, paints and glass  ', 'Hardware Store')
import('G', '52', '4', '7', '', 'Retail sale of books, newspapers and stationery  ', '')
import('G', '52', '4', '7', '1', 'Retail sale of books', 'Books')
import('G', '52', '4', '7', '2', 'Retail sale of newspapers', 'Newspaper')
import('G', '52', '4', '7', '3', 'Retail sale of stationery', 'Stationery')
import('G', '52', '4', '8', '', 'Other retail sale in specialized stores  ', 'Other Retail')
import('G', '52', '4', '8', '1', 'Retail sale of animal care products', 'Pet Store')
import('G', '52', '4', '8', '2', 'Retail sale of arts and crafts', 'Art')
import('G', '52', '4', '8', '3', 'Retail sale of boat supplies', 'Boat Supplies')
import('G', '52', '4', '8', '4', 'Retail sale of coins and stamps', 'Coins and Stamps')
import('G', '52', '4', '8', '5', 'Retail sale of costumes', 'Costumes')
import('G', '52', '4', '8', '6', 'Retail sale of eyewear and eyecare', 'Optical Store')
import('G', '52', '4', '8', '7', 'Retail sale of fishing supplies', 'Fishing')
import('G', '52', '4', '8', '8', 'Retail sale of frames', 'Frames')
import('G', '52', '4', '8', '9', 'Retail sale of flowers', 'Florist')
import('G', '52', '4', '8', '10', 'Retail sale of funeral goods', 'Funeral Goods')
import('G', '52', '4', '8', '11', 'Retail sale of jewelry', 'Jewelry')
import('G', '52', '4', '8', '12', 'Retail sale of knives', 'Knives')
import('G', '52', '4', '8', '13', 'Retail sale of media', 'Entertainment')
import('G', '52', '4', '8', '14', 'Retail sale of metal work', 'Metal Work')
import('G', '52', '4', '8', '15', 'Retail sale of musical instruments', 'Musical Instruments')
import('G', '52', '4', '8', '16', 'Retail sale of office supplies', 'Office Supplies')
import('G', '52', '4', '8', '17', 'Retail sale of photographic goods', 'Photo Store')
import('G', '52', '4', '8', '18', 'Retail sale of sporting goods', 'Sporting Goods')
import('G', '52', '4', '8', '19', 'Retail sale of souvenirs', 'Souvenirs')
import('G', '52', '4', '8', '20', 'Retail sale of toys', 'Toys')
import('G', '52', '4', '8', '21', 'Retail sale wedding decorations and related goods', 'Wedding')
import('G', '52', '4', '8', '22', 'Retail sale of wood work', 'Wood Work')
import('G', '52', '5', '', '', 'Retail sale of second-hand goods in stores  ', '')
import('G', '52', '5', '0', '', 'Retail sale of second-hand goods in stores ', 'Pawn Shop')
import('G', '52', '5', '0', '1', 'Antiques', 'Antiques')
import('', '', '', '', '', '', '')
import('G', '52', '6', '', '', 'Retail sale not in stores  ', '')
import('G', '52', '6', '1', '', 'Retail sale via mail order houses  ', '')
import('G', '52', '6', '2', '', 'Retail sale via stalls and markets  ', '')
import('G', '52', '6', '3', '', 'Other non-store retail sale  ', '')
import('G', '52', '7', '', '', 'Repair of personal and household goods  ', 'Repair')
import('G', '52', '7', '1', '', 'Repair of boots, shoes and other articles of leather  ', '')
import('G', '52', '7', '2', '', 'Repair of electrical household goods  ', '')
import('G', '52', '7', '3', '', 'Repair of watches, clocks and jewellery  ', '')
import('G', '52', '7', '4', '', 'Repair n.e.c.  ', '')
import('', '', '', '', '', '', '')
import('H', '', '', '', '', 'Hotels and restaurants  ', '')
import('H', '55', '', '', '', 'Hotels and restaurants  ', '')
import('H', '55', '1', '', '', 'Hotels ', 'Hotel')
import('H', '55', '1', '1', '', 'Hotels and motels, with restaurant  ', 'Hotel with Restaurants')
import('H', '55', '1', '2', '', 'Hotels and motels, without restaurant  ', 'Hotel without Restaurants')
import('H', '55', '2', '', '', 'Camping sites and other provision of short-stay accommodation  ', '')
import('H', '55', '2', '1', '', 'Youth hostels and mountain refuges', 'Hostel')
import('H', '55', '2', '2', '', 'Camping sites, including caravan sites  ', '')
import('H', '55', '2', '3', '', 'Other provision of lodgings n.e.c.', '')
import('H', '55', '2', '3', '1', 'Bed and breakfasts', 'Bed and Breakfasts')
import('H', '55', '2', '3', '2', 'Renting of rooms of private homes and guest houses', 'Affitacamere')
import('H', '55', '2', '3', '3', 'Apartment rental', 'Apartment Rental')
import('H', '55', '3', '', '', 'Restaurants ', '')
import('H', '55', '3', '0', '', 'Restaurants  ', 'Restaurant')
import('H', '55', '3', '0', '1', 'Gelateria', 'Gelateria')
import('H', '55', '3', '0', '2', 'Pizzeria', 'Pizzeria')
import('H', '55', '4', '', '', 'Bars ', '')
import('H', '55', '4', '0', '', 'Bars ', 'Bars')
import('H', '55', '5', '', '', 'Canteens and catering  ', '')
import('H', '55', '5', '1', '', 'Canteens ', '')
import('H', '55', '5', '2', '', 'Catering', '')
import('', '', '', '', '', '', '')
import('I', '', '', '', '', 'Transport, Storage and Communication', '')
import('I', '63', '', '', '', 'Supporting and auxiliary transport activities; activities of travel agencies', '')
import('I', '63', '1', '', '', 'Cargo handling and storage  ', '')
import('I', '63', '1', '1', '', 'Cargo handling', '')
import('I', '63', '1', '2', '', 'Storage and warehousing', '')
import('I', '63', '2', '', '', 'Other supporting transport activities  ', '')
import('I', '63', '2', '1', '', 'Other supporting land transport activities', '')
import('I', '63', '2', '2', '', 'Other supporting water transport activities', '')
import('I', '63', '2', '3', '', 'Other supporting air transport activities', '')
import('I', '63', '3', '', '', 'Activities of travel agencies and tour operators; tourist assistance activities n.e.c.  ', '')
import('I', '63', '3', '0', '', 'Activities of travel agencies and tour operators; tourist assistance activities n.e.c.  ', 'Travel Agency')
import('I', '63', '4', '', '', 'Activities of other transport agencies', '')
import('I', '63', '4', '0', '', 'Activities of other transport agencies', 'Transportation')
import('I', '63', '4', '0', '1', 'Delivery and mail services', 'Delivery')
import('', '', '', '', '', '', '')
import('J', '', '', '', '', 'Financial intermediation  ', '')
import('J', '65', '', '', '', 'Financial intermediation, except insurance and pension funding  ', '')
import('J', '65', '1', '', '', 'Monetary intermediation  ', '')
import('J', '65', '1', '1', '', 'Central banking  ', 'Bank')
import('J', '65', '1', '2', '', 'Other monetary intermediation  ', '')
import('J', '65', '1', '2', '1', 'Cash Exchange', 'Exchange')
import('J', '65', '1', '2', '2', 'Money Transfer', 'Money Transfer')
import('J', '65', '2', '', '', 'Other financial intermediation  ', '')
import('J', '65', '2', '1', '', 'Financial leasing  ', '')
import('J', '65', '2', '2', '', 'Other credit granting  ', '')
import('J', '65', '2', '3', '', 'Other financial intermediation n.e.c.  ', '')
import('', '', '', '', '', '', '')
import('J', '66', '', '', '', 'Insurance and pension funding, except compulsory social security  ', '')
import('J', '66', '0', '', '', 'Insurance and pension funding, except compulsory social security  ', '')
import('J', '66', '0', '1', '', 'Life insurance  ', '')
import('J', '66', '0', '2', '', 'Pension funding  ', '')
import('J', '66', '0', '3', '', 'Non-life insurance  ', '')
import('', '', '', '', '', '', '')
import('J', '67', '', '', '', 'Activities auxiliary to financial intermediation  ', '')
import('J', '67', '1', '', '', 'Activities auxiliary to financial intermediation, except insurance and pension funding  ', '')
import('J', '67', '1', '1', '', 'Administration of financial markets  ', '')
import('J', '67', '1', '2', '', 'Security broking and fund management  ', '')
import('J', '67', '1', '3', '', 'Activities auxiliary to financial intermediation n.e.c.  ', '')
import('J', '67', '2', '', '', 'Activities auxiliary to insurance and pension funding  ', '')
import('J', '67', '2', '0', '', 'Activities auxiliary to insurance and pension funding', '')
import('', '', '', '', '', '', '')
import('K', '', '', '', '', 'Real estate, renting and business activities  ', '')
import('K', '70', '', '', '', 'Real estate activities  ', '')
import('K', '70', '1', '', '', 'Real estate activities with own property', '')
import('K', '70', '1', '1', '', 'Development and selling of real estate  ', '')
import('K', '70', '1', '2', '', 'Buying and selling of own real estate  ', '')
import('K', '70', '2', '', '', 'Letting of own property  ', '')
import('K', '70', '2', '0', '', 'Letting of own property  ', '')
import('K', '70', '3', '', '', 'Real estate activities on a fee or contract basis  ', '')
import('K', '70', '3', '1', '', 'Real estate agencies  ', 'Real Estate')
import('K', '70', '3', '2', '', 'Management of real estate on a fee or contract basis  ', '')
import('', '', '', '', '', '', '')
import('K', '71', '', '', '', 'Renting of machinery and equipment without operator and of personal and household goods  ', '')
import('K', '71', '1', '', '', 'Renting of automobiles  ', '')
import('K', '71', '1', '0', '', 'Renting of automobiles  ', 'Car Rental')
import('K', '71', '2', '', '', 'Renting of other transport equipment  ', '')
import('K', '71', '2', '1', '', 'Renting of other land transport equipment  ', '')
import('K', '71', '2', '2', '', 'Renting of water transport equipment  ', '')
import('K', '71', '2', '3', '', 'Renting of air transport equipment  ', '')
import('K', '71', '3', '', '', 'Renting of other machinery and equipment  ', '')
import('K', '71', '3', '1', '', 'Renting of agricultural machinery and equipment  ', '')
import('K', '71', '3', '2', '', 'Renting of construction and civil engineering machinery and equipment  ', '')
import('K', '71', '3', '3', '', 'Renting of office machinery and equipment, including computers  ', '')
import('K', '71', '3', '4', '', 'Renting of other machinery and equipment n.e.c.  ', '')
import('K', '71', '4', '', '', 'Renting of personal and household goods n.e.c.  ', '')
import('K', '71', '4', '0', '', 'Renting of personal and household goods n.e.c.  ', '')
import('K', '71', '4', '0', '1', 'Renting of personal goods only', '')
import('K', '71', '4', '0', '2', 'Renting of household goods only', '')
import('K', '71', '4', '0', '3', 'Renting of both personal and household goods', '')
import('', '', '', '', '', '', '')
import('K', '72', '', '', '', 'Computer and related activities  ', '')
import('K', '72', '1', '', '', 'Hardware consultancy  ', '')
import('K', '72', '1', '0', '', 'Hardware consultancy  ', '')
import('K', '72', '2', '', '', 'Software consultancy and supply  ', '')
import('K', '72', '2', '0', '', 'Software consultancy and supply  ', '')
import('K', '72', '3', '', '', 'Data processing  ', '')
import('K', '72', '3', '0', '', 'Data processing  ', '')
import('K', '72', '4', '', '', 'Database activities  ', '')
import('K', '72', '4', '0', '', 'Database activities  ', '')
import('K', '72', '5', '', '', 'Maintenance and repair of office, accounting and computing machinery  ', '')
import('K', '72', '5', '0', '', 'Maintenance and repair of office, accounting and computing machinery  ', 'Computer Services')
import('K', '72', '6', '', '', 'Other computer related activities  ', '')
import('K', '72', '6', '0', '', 'Other computer related activities  ', '')
import('', '', '', '', '', '', '')
import('K', '74', '', '', '', 'Other business activities  ', '')
import('K', '74', '1', '', '', 'Legal, accounting, book-keeping and auditing activities; tax consultancy; market research and public opinion polling; business and management consultancy; holdings ', '')
import('K', '74', '1', '1', '', 'Legal activities  ', '')
import('K', '74', '1', '2', '', 'Accounting, book-keeping and auditing activities; tax consultancy  ', '')
import('K', '74', '1', '3', '', 'Market research and public opinion polling  ', '')
import('K', '74', '1', '4', '', 'Business and management consultancy activities  ', '')
import('K', '74', '1', '5', '', 'Management activities of holding companies  ', '')
import('K', '74', '2', '', '', 'Architectural and engineering activities and related technical consultancy  ', '')
import('K', '74', '2', '0', '', 'Architectural and engineering activities and related technical consultancy  ', '')
import('K', '74', '3', '', '', 'Technical testing and analysis  ', '')
import('K', '74', '3', '0', '', 'Technical testing and analysis  ', '')
import('K', '74', '4', '', '', 'Advertising', '')
import('K', '74', '4', '0', '', 'Advertising', '')
import('K', '74', '5', '', '', 'Labour recruitment and provision of personnel  ', '')
import('K', '74', '5', '0', '', 'Labour recruitment and provision of personnel  ', '')
import('K', '74', '6', '', '', 'Investigation and security activities  ', '')
import('K', '74', '6', '0', '', 'Investigation and security activities  ', '')
import('K', '74', '7', '', '', 'Industrial cleaning  ', '')
import('K', '74', '7', '0', '', 'Industrial cleaning  ', '')
import('K', '74', '8', '', '', 'Miscellaneous business activities n.e.c.  ', '')
import('K', '74', '8', '1', '', 'Photographic activities  ', 'Photographer')
import('K', '74', '8', '2', '', 'Packaging activities  ', '')
import('K', '74', '8', '3', '', 'Secretarial and translation activities  ', '')
import('K', '74', '8', '4', '', 'Other business activities n.e.c.  ', '')
import('K', '74', '8', '5', '', 'Photocopy activities', 'Photocopy')
import('K', '74', '8', '6', '', 'Graphic design activities', 'Graphic Design')
import('', '', '', '', '', '', '')
import('O', '', '', '', '', 'Other community, social and personal service activities  ', '')
import('O', '92', '', '', '', 'Recreational, cultural and sporting activities  ', '')
import('O', '92', '1', '', '', 'Motion picture and video activities  ', '')
import('O', '92', '1', '1', '', 'Motion picture and video production  ', '')
import('O', '92', '1', '2', '', 'Motion picture and video distribution  ', '')
import('O', '92', '1', '3', '', 'Motion picture projection  ', '')
import('O', '92', '2', '', '', 'Radio and television activities  ', '')
import('O', '92', '2', '0', '', 'Radio and television activities  ', '')
import('O', '92', '2', '0', '1', 'Radio activities', '')
import('O', '92', '2', '0', '2', 'Television activities', '')
import('O', '92', '3', '', '', 'Other entertainment activities  ', '')
import('O', '92', '3', '1', '', 'Artistic and literary creation and interpretation  ', '')
import('O', '92', '3', '1', '1', 'Artistic creation and interpretation', '')
import('O', '92', '3', '1', '2', 'Literary creation and interpretation', '')
import('O', '92', '3', '2', '', 'Operation of arts facilities  ', '')
import('O', '92', '3', '3', '', 'Fair and amusement park activities  ', '')
import('O', '92', '3', '4', '', 'Other entertainment activities n.e.c.  ', '')
import('O', '92', '4', '', '', 'News agency activities  ', '')
import('O', '92', '4', '0', '', 'News agency activities  ', '')
import('O', '92', '5', '', '', 'Library, archives, museums and other cultural activities  ', '')
import('O', '92', '5', '1', '', 'Library and archives activities  ', '')
import('O', '92', '5', '2', '', 'Museums activities and preservation of historical sites and buildings  ', '')
import('O', '92', '5', '2', '1', 'Museums activities', '')
import('O', '92', '5', '2', '2', 'Preservation of historical sites and buildings activities', '')
import('O', '92', '5', '3', '', 'Botanical and zoological gardens and nature reserves activities  ', '')
import('O', '92', '6', '', '', 'Sporting activities  ', '')
import('O', '92', '6', '1', '', 'Operation of sports arenas and stadiums  ', '')
import('O', '92', '6', '2', '', 'Other sporting activities  ', '')
import('O', '92', '7', '', '', 'Other recreational activities  ', '')
import('O', '92', '7', '1', '', 'Gambling and betting activities  ', '')
import('O', '92', '7', '2', '', 'Other recreational activities n.e.c.  ', 'Recreational Activities')
import('', '', '', '', '', '', '')
import('O', '93', '', '', '', 'Other service activities  ', '')
import('O', '93', '0', '', '', 'Other service activities  ', '')
import('O', '93', '0', '1', '', 'Washing and dry-cleaning of textile and fur products  ', '')
import('O', '93', '0', '1', '1', 'Dry-cleaners', 'Dry Cleaner')
import('O', '93', '0', '1', '2', 'Laundrymat', 'Laundrymat')
import('O', '93', '0', '2', '', 'Hairdressing and other beauty treatment  ', '')
import('O', '93', '0', '2', '1', 'Hair Salon', 'Hair Salon')
import('O', '93', '0', '2', '2', 'Nail Salon', 'Nail Salon')
import('O', '93', '0', '2', '3', 'Spa', 'Spa')
import('O', '93', '0', '2', '4', 'Masseuse', 'Masseuse')
import('O', '93', '0', '2', '5', 'Tattoo and Piercing', 'Tattoo and Piercing')
import('O', '93', '0', '3', '', 'Funeral and related activities  ', 'Funeral Services')
import('O', '93', '0', '4', '', 'Physical well-being activities  ', 'Fitness')
import('O', '93', '0', '5', '', 'Other service activities n.e.c.', '')
import('O', '93', '0', '5', '1', 'Tailor', 'Tailor')